-- Add schema_version, warnings, and attempt_count to ai_extraction_runs.
-- schema_version is stored separately from prompt_version so both can evolve independently.
-- warnings is a jsonb array of string messages generated by the extraction worker.
-- attempt_count records which attempt this row represents.

alter table public.ai_extraction_runs
  add column if not exists schema_version text,
  add column if not exists warnings       jsonb,
  add column if not exists attempt_count  integer not null default 1;

-- Prevent two completed runs with the same extraction identity on the same document.
-- Multiple running/failed rows are still allowed (supports retries and concurrent-worker detection).
create unique index if not exists idx_ai_extraction_runs_completed_unique
  on public.ai_extraction_runs(document_id, provider, model, prompt_version, schema_version)
  where status = 'completed';

-- Faster eligibility lookup used by every extraction batch.
create index if not exists idx_ai_extraction_runs_doc_provider_status
  on public.ai_extraction_runs(document_id, provider, status);
